# name: try ... catch
# key: try
# --
try
  $1
catch ${2:err}
  $0
end
