# name: try
# key: try
# --
try {
	$0
} catch (${1:Exception} $e) {
}