# name: try
# key: try
# --
try
	$1
catch ${2:error}
	$0